name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email jean.carlo.polo@uel.br
          git config --global user.name tonhao mototaxi
          git status
          git remote add origin https://${{secrets.token}}github.com/jeancarlopolo/portfolio
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f